# Generated by Django 4.2.3 on 2023-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('start', models.DateTimeField(auto_now=True)),
                ('End', models.DateTimeField()),
            ],
        ),
    ]
