# Generated by Django 4.2.3 on 2023-11-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_search_date_alter_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
