# Generated by Django 4.2.3 on 2023-11-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='earnings',
            field=models.FloatField(default=0.0),
        ),
    ]
