# Generated by Django 4.2.3 on 2023-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
