# Generated by Django 4.2.3 on 2023-11-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads_3rd_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='payment_info',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('USD', 'USD')], default=' ', max_length=50),
        ),
    ]
