# Generated by Django 4.2.3 on 2023-11-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_payment_method_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
