# Generated by Django 4.2.3 on 2023-11-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ads_3rd_party_url_ads_3rd_party_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='gen_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('brodcast_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='per_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('brodcast_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
